### ISSUE TITLE
Error starting VM in Linux Mint 18.1 64-bit.

### ISSUE THREAD

**Issue by musiciancodes** [miguelgrinberg/microflack_admin#1]
Following the instructions sent in the tutorial email, I installed virtualbox + vagrant.
<code>$vagrant up</code> leaves me the error:

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "9e3e6de0-4150-48b5-be7c-7c7ec960c03d", "--type", "headless"]

Stderr: VBoxManage: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

I'm not sure how to proceed (I've looked on SO/google and tried a couple solutions) - any help would be appreciated.

**Comment by miguelgrinberg** [comment]
@y3l2n Is this an older computer? This problem occurs because the CPU in your computer is not configured properly for virtualization, or is too old and does not support that. The settings to enable virtualization should be in your computer's setup.

The problem usually occurs with 64-bit VMs. Older CPUs may not have the functionality required to support 64-bit VMs, but they are usually okay with 32-bit VMs. If you can't figure out how to make this work, another thing you can try is replace the 64-bit guest image with a 32-bit equivalent image. In file `Vagrantfile`, change `ubuntu/xenial64` to `ubuntu/xenial32`.

**Comment by musiciancodes** [comment]
I tried editing the image to 32 bit, but I get the same error. I'll keep
troubleshooting.

On May 16, 2017 1:04 AM, "Miguel Grinberg" <notifications@github.com> wrote:

@y3l2n <https://github.com/y3l2n> Is this an older computer? This problem
occurs because the CPU in your computer is not configured properly for
virtualization, or is too old and does not support that. The settings to
enable virtualization should be in your computer's setup.

The problem usually occurs with 64-bit VMs. Older CPUs may not have the
functionality required to support 64-bit VMs, but they are usually okay
with 32-bit VMs. If you can't figure out how to make this work, another
thing you can try is replace the 64-bit guest image with a 32-bit
equivalent image. In file Vagrantfile, change ubuntu/xenial64 to
ubuntu/xenial32.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/miguelgrinberg/microflack_admin/issues/1#issuecomment-301684370>,
or mute the thread

**Comment by miguelgrinberg** [comment]
What machine is this? Do you have the specific CPU model?

As I said above, some computers come with virtualization support in the CPU disabled. You just need to get in the computer's setup and enable it.

**Comment by miguelgrinberg** [comment]
@y3l2n hey, so tomorrow I'm going to be at the conference around 11am. If you want help in figuring this out, look for me or let me know where to find you. I'm probably going to be sitting in some corner getting my laptop ready for the class.

**Comment by musiciancodes** [comment]
I have a morning tutorial, so I'll try to find you around 12:30. I'll look
for you near the room we're meeting in.

**Comment by musiciancodes** [comment]
I got it all sorted - looking forward to your tutorial!

Yulan

**Comment by miguelgrinberg** [comment]
@y3l2n out of curiosity (and in case somebody else has this problem), how did you fix it?

**Comment by musiciancodes** [comment]
Honestly - I switched to a different computer, so that's not a real
solution.
