### ISSUE TITLE
I can't run any of the commands in the VM

### ISSUE THREAD

**Issue by okeyokoro** [miguelgrinberg/microflack_admin#5]
Steps to recreate:

- run on a 2018 MacBook Pro
- install the latest Virtualbox for Mac
- install the latest Vagrant
- git clone the repo
- `cd microflack_admin`
- run `vagrant up   # takes about 20 minutes on first run`

At this point vagrant outputs the message:

```bash
default: MicroFlack is now deployed!
default: - Run source ~/.profile or log back in to update your environment.
default: - You may need some variables from /home/ubuntu/.profile if you intend to run services in another host.
```

When I navigate to `192.168.33.10/stats` I get to see the HAProxy dashboard:

![haproxy](https://i.imgur.com/yqs8ppa.png)
When I navigate to `192.168.33.10` I get to see the ui. But the UI behaves weirdly. When I type in a message, the UI doesn't get updated. Even when I log in. The UI doesn't update.

**But most annoying of all,** when I run `vagrant ssh` and get into the vm. The following commands get the following results:

```bash
vagrant@ubuntu-xenial:~$ ls

# i get nothing

vagrant@ubuntu-xenial:~$ docker ps

Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/json: dial unix /var/run/docker.sock: connect: permission denied

vagrant@ubuntu-xenial:~$ sudo docker ps  # just tried my luck. but Miguel didn't have to use sudo during his pycon presentation (I discovered it (& this repo) on YouTube after searching for how to get started with microservices)

CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                               NAMES
b1548439db30        microflack_socketio:latest              "./boot.sh"              16 minutes ago      Up 16 minutes       0.0.0.0:32772->5000/tcp             socketio_b1548439db30
b2b9acbf16c5        microflack_messages:latest              "./boot.sh"              16 minutes ago      Up 16 minutes       0.0.0.0:32771->5000/tcp             messages_b2b9acbf16c5
dc1ef3b913d0        microflack_tokens:latest                "./boot.sh"              16 minutes ago      Up 16 minutes       0.0.0.0:32770->5000/tcp             tokens_dc1ef3b913d0
effe5aa3d14b        microflack_users:latest                 "./boot.sh"              16 minutes ago      Up 16 minutes       0.0.0.0:32769->5000/tcp             users_effe5aa3d14b
576818e3a6ab        microflack_ui:latest                    "./boot.sh"              16 minutes ago      Up 16 minutes       0.0.0.0:32768->5000/tcp             ui_576818e3a6ab
625e26bdcf33        miguelgrinberg/easy-lb-haproxy:latest   "/docker-entrypoint.…"   20 minutes ago      Up 20 minutes       0.0.0.0:80->80/tcp                  lb
6aca487fcd5e        redis:3.2-alpine                        "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes       0.0.0.0:6379->6379/tcp              redis
7a81ffbf1332        mysql:5.7                               "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes       0.0.0.0:3306->3306/tcp, 33060/tcp   mysql
2d96be43a0fb        miguelgrinberg/easy-etcd:latest         "./boot.sh"              22 minutes ago      Up 22 minutes       0.0.0.0:2379-2380->2379-2380/tcp    etcd
ec0297451646        gliderlabs/logspout:latest              "/bin/logspout"          22 minutes ago      Up 22 minutes       0.0.0.0:1095->80/tcp                logspout

vagrant@ubuntu-xenial:~$ mfenv

mfenv: command not found   # the main problem I'm having
```

Before I decided to create this issue. I read up on Vagrant to search for possible solutions. I came up with the following:

```bash
vagrant@ubuntu-xenial:~$ cd /vagrant   # where shared folders in vagrant appear in the VM
vagrant@ubuntu-xenial:/vagrant$ ls
bin  install  LICENSE  mfvars  README.md  ubuntu-xenial-16.04-cloudimg-console.log  Vagrantfile

vagrant@ubuntu-xenial:/vagrant$ /vagrant/bin/mfenv   # the command runs. But, the needed ENVIRONMENT VARIABLES are missing. Perhaps this is the root cause of my woes...

ETCD="http://:2379"
REDIS=":6379"
LB="http://"
SECRET_KEY=""
JWT_SECRET_KEY=""
/vagrant/bin/mfenv: line 14: /home/vagrant/.mysql_passwords: No such file or directory
```

**Comment by miguelgrinberg** [comment]
Did you use the same ubuntu box that I used? Sounds like you have `vagrant` as main account, while I have `ubuntu`.

[this line](https://github.com/miguelgrinberg/microflack_admin/blob/master/install/setup-all-in-one.sh#L17) is supposed to add the `bin` directory with all the scripts to your path. You will need to debug this to find out why that path isn't being updated.

Regarding the docker command not working, [this line](https://github.com/miguelgrinberg/microflack_admin/blob/master/install/setup-host.sh#L13) configures the `ubuntu` account so that it can use docker without being super user.

**Comment by okeyokoro** [comment]
Thanks for following up @miguelgrinberg, I'm a fan 🙂.

_Q: "Did you use the same ubuntu box that I used?"_

A: I think so, I simply ran `vagrant up`. I didn't change the Vagrantfile. I assume [this line](https://github.com/miguelgrinberg/microflack_admin/blob/master/Vagrantfile#L16) picks the right ubuntu box

_Q: "Sounds like you have vagrant as main account, while I have ubuntu"_

A: This is accurate. Although, I am not sure why this is so.  This is my first dance with Vagrant

Do you think the problem could be the version of Vagrant I'm running? What version of Vagrant did you demo with?

**Comment by miguelgrinberg** [comment]
@okeyokoro the problem is likely not vagrant, but the version of the box, which is the image from which the vm is constructed. You can run the `vagrant box list` to see what you have. Here is my output:

    ubuntu/xenial64 (virtualbox, 20190123.0.1)

**Comment by okeyokoro** [comment]
```
$ vagrant box list
ubuntu/xenial64 (virtualbox, 20190511.0.0)
```

`...123.0.1` vs `...511.0.0`

okay, do you have any recommendations for making this diff go away?

**Comment by miguelgrinberg** [comment]
Hmm. I tested the latest ubuntu box and yes, it appears they have switched the default user from `ubuntu` to `vagrant`. An easy thing you can do to switch to the `ubuntu` account is to type this under the `vagrant` account:

    $ sudo su ubuntu
    $ cd
    $ source ~/.profile

From then on, you would be using the `ubuntu` account and everything should work as expected.

**Comment by miguelgrinberg** [comment]
To address this problem I'm going to change the install script to use the `vagrant` account, since that is the default in current versions of the ubuntu cloud image.

**Comment by miguelgrinberg** [comment]
If you regenerate the VM after updating this repository you should be able to work in the default vagrant account.
